/// <reference types="vite/client" />

interface ImportMetaEnv {
  /** Optional HTTPS endpoint that receives contact form submissions. */
  readonly VITE_CONTACT_ENDPOINT?: string;
  /** Optional Google Maps embed URL for the contact section. */
  readonly VITE_MAP_EMBED_URL?: string;
}

interface ImportMeta {
  readonly env: ImportMetaEnv;
}

/** Generated by the `lumen-local-photos` Vite plugin from `src/assets/photos`. */
declare module 'virtual:local-photos' {
  export const localPhotos: Record<
    string,
    { readonly src: string; readonly width: number; readonly height: number }
  >;
}
